image: hashicorp/terraform:light

stages:
  - deploy

terraform-prod:
  stage: deploy
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: service-account.json
  script:
    - init
    - workspace new prod
    - workspace select prod
    - plan -out=plan.tfplan
    - apply plan.tfplan -auto-approve -input=false
  only:
    - master