image:
  name: hashicorp/terraform:1.0.8
  entrypoint:
    - /usr/bin/env
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

stages:
  - deploy

terraform-prod:
  stage: deploy
  before_script:
    - echo $GOOGLE_SA_JSON > service-account.json
    - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service-account.json
  script:
    - terraform -chdir=infrastructure init
    - terraform -chdir=infrastructure workspace select prod ||
      terraform -chdir=infrastructure workspace new prod
    - terraform -chdir=infrastructure validate
    - terraform -chdir=infrastructure plan -out=plan.tfplan -var-file=prod.tfvars
    - terraform -chdir=infrastructure apply plan.tfplan
  only:
    - master
