image: hashicorp/terraform:light

terraform-prod:
  before_script:
    - echo $GOOGLE_SA_JSON > service_account.json
    - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service_account.json
  script:
    - terraform init
    - terraform workspace select prod || terraform workspace new prod
    - terraform plan -out=plan.tfplan
    - terraform apply plan.tfplan -auto-approve -input=false
