image: docker:latest

variables:
  DOCKER_DRIVER: overlay

stages:
  - test
  - package
  - deploy

test:
  image: hashicorp/terraform:light
  stage: test
  script:
  - terraform init
  - terraform plan

package:
  image: hashicorp/terraform:light
  stage: test
  script:
  - terraform init
  - terraform plan

deploy:
  image: hashicorp/terraform:light
  stage: test
  script:
  - terraform init
  - terraform plan