image:
  name: hashicorp/terraform:light
  entrypoint:
    - /usr/bin/env
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

stages:
  - deploy

terraform-prod:
  stage: deploy
  before_script:
    - echo $GOOGLE_SA_JSON > service-account.json
    - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service-account.json
  script:
    - terraform -chdir=src init
    - terraform -chdir=src workspace select prod || terraform workspace new prod
    - terraform -chdir=src validate
    - terraform -chdir=src plan -out=plan.tfplan -var 'project=$GCP_PROJECT'
    - terraform -chdir=src apply plan.tfplan
  only:
    - master