name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.6.0'
        with:
          workload_identity_provider: projects/123456789/locations/global/workloadIdentityPools/automation-pool/providers/my-provider
          service_account: automation@automation-12345.iam.gserviceaccount.com
      - run: terraform -chdir=infrastructure init
      - run: terraform validate
      - run: terraform apply

#   deploy-prod:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 1.1.5
#       - run: terraform -chdir=infrastructure init
#       - run: terraform apply
